### PR TITLE
Update composer.json: added support to Symfony 6.x

### PR DESCRIPTION
**Pull request by hegdedr**
Update composer.json: added support to Symfony 6.x

### CODE REVIEW

**Comment by hegdedr** [comment]
Yes

**Comment by igordeveloper** [comment]
> > Could you please release this pull request for use in SF 6?
> 
> I think I don't have access to to release



#299

**Comment by igordeveloper** [comment]
@rdohms could you please check this PR? thank you.

**Review by hegdedr — COMMENTED** [review]
looks fine

**Comment by rdohms** [comment]
Solved by #302

**Pull request closed without merging**
