### PR TITLE
Support for flex

### PR DESCRIPTION
**Pull request by Webonaute**
Fix symfony/symfony package to work with flex.
Cleanup some code. 
Removed support for php < 7.2 and symfony < 3.4
Removed composer.lock which cause conflict.

**## Note that this PR require major version increase.**

### CODE REVIEW

**Comment by BernhardWebstudio** [comment]
That's some good work! I was asking myself, why exactly do you drop support for PHP 7.0, 7.1? symfony/flex at least supports ^7.0...

**Comment by Webonaute** [comment]
actually, symfony 4 require minimum version of php 7.1.13 http://symfony.com/doc/current/reference/requirements.html

I fixed composer and travis.

**Comment by Webonaute** [comment]
by the composer required package it's : 7.1.3
symfony/yaml : https://github.com/symfony/yaml/blob/master/composer.json php 7.1.3
symfony/framework-bundle : https://github.com/symfony/yaml/blob/master/composer.json php 7.1.3
symfony/form : https://github.com/symfony/yaml/blob/master/composer.json php 7.1.3

**Comment by Webonaute** [comment]
oups!

**Comment by Webonaute** [comment]
I think I did the maximum I can for now. probably have to update the usage of the container directly. and instead of class with %config%, use DI to overwrite default class from dms.filter global config.

**Comment by rdohms** [comment]
Ok, let me clean up and look into what this means for the container usage, thanks for the work @Webonaute

**Comment by rdohms** [comment]
I have split the work here into:
- #41: Cleanup and upgrades
- #42: Flex support

Please refer to these PRs for the final versions.
@Webonaute thanks for the work done so far.

**Comment by Webonaute** [comment]
when are you gonna do a first 4.0 version?

**Comment by rdohms** [comment]
Would love to give this a test in a flex setup, but i have none at the moment, could you do some testing with that branch?

**Comment by Webonaute** [comment]
which branch?

**Comment by Webonaute** [comment]
actually I use the change on my PR in production since some months already.

**Comment by rdohms** [comment]
Alright, so no further changes required, i'll see if i can get a release done by the weekend then.

**Pull request closed without merging**
